export const THEMES = [
  { value: "theme:adult%20cast", label: "Adult Cast" },
  { value: "theme:anthropomorphic", label: "Anthropomorphic" },
  { value: "theme:cgdct", label: "CGDCT" },
  { value: "theme:childcare", label: "Childcare" },
  { value: "theme:combat%20sports", label: "Combat Sports" },
  { value: "theme:crossdressing", label: "Crossdressing" },
  { value: "theme:delinquents", label: "Delinquents" },
  { value: "theme:detective", label: "Detective" },
  { value: "theme:educational", label: "Educational" },
  { value: "theme:gag%20humor", label: "Gag Humor" },
  { value: "theme:gore", label: "Gore" },
  { value: "theme:harem", label: "Harem" },
  { value: "theme:high%20stakes%20game", label: "High Stakes Game" },
  { value: "theme:historical", label: "Historical" },
  { value: "theme:idols%20female", label: "Idols (Female)" },
  { value: "theme:idols%20male", label: "Idols (Male)" },
  { value: "theme:isekai", label: "Isekai" },
  { value: "theme:iyashikei", label: "Iyashikei" },
  { value: "theme:love%20polygon", label: "Love Polygon" },
  { value: "theme:love%20status%20quo", label: "Love Status Quo" },
  { value: "theme:magical%20sex%20shift", label: "Magical Sex Shift" },
  { value: "theme:mahou%20shoujo", label: "Mahou Shoujo" },
  { value: "theme:martial%20arts", label: "Martial Arts" },
  { value: "theme:mecha", label: "Mecha" },
  { value: "theme:medical", label: "Medical" },
  { value: "theme:military", label: "Military" },
  { value: "theme:music", label: "Music" },
  { value: "theme:mythology", label: "Mythology" },
  { value: "theme:organized%20crime", label: "Organized Crime" },
  { value: "theme:otaku%20culture", label: "Otaku Culture" },
  { value: "theme:parody", label: "Parody" },
  { value: "theme:performing%20arts", label: "Performing Arts" },
  { value: "theme:pets", label: "Pets" },
  { value: "theme:psychological", label: "Psychological" },
  { value: "theme:racing", label: "Racing" },
  { value: "theme:reincarnation", label: "Reincarnation" },
  { value: "theme:reverse%20harem", label: "Reverse Harem" },
  { value: "theme:samurai", label: "Samurai" },
  { value: "theme:school", label: "School" },
  { value: "theme:showbiz", label: "Showbiz" },
  { value: "theme:space", label: "Space" },
  { value: "theme:strategy%20game", label: "Strategy Game" },
  { value: "theme:super%20power", label: "Super Power" },
  { value: "theme:survival", label: "Survival" },
  { value: "theme:team%20sports", label: "Team Sports" },
  { value: "theme:time%20travel", label: "Time Travel" },
  { value: "theme:urban%20fantasy", label: "Urban Fantasy" },
  { value: "theme:vampire", label: "Vampire" },
  { value: "theme:video%20game", label: "Video Game" },
  { value: "theme:villainess", label: "Villainess" },
  { value: "theme:visual%20arts", label: "Visual Arts" },
  { value: "theme:workplace", label: "Workplace" },
];
